# Generated by Django 2.2.7 on 2019-11-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('ordNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('carNumber', models.IntegerField(blank=True, null=True)),
                ('trainIndex', models.IntegerField(blank=True, null=True)),
                ('trainNumber', models.IntegerField(blank=True, null=True)),
                ('carStatus', models.CharField(max_length=40)),
                ('invoiceId', models.IntegerField(blank=True, null=True)),
                ('invoiceNumber', models.CharField(max_length=8)),
                ('stateId', models.IntegerField(blank=True, null=True)),
                ('lastOperDt', models.DateTimeField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
